/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/6N4qS95eAKQ
 */


export function NattyCard() {
  return (
    <div className="w-[300px] h-[400px] border border-gray-200 rounded-lg dark:border-gray-800">
      <div>
        <div className="flex flex-col items-center justify-center space-y-4 p-8">
          <div className="space-y-2 text-center">
            <h3 className="text-lg font-bold">Your Nattiness</h3>
            <p className="text-sm text-gray-500 dark:text-gray-400">Scan the QR code to reveal your true nattiness.</p>
            <p className="text-xs text-gray-500 dark:text-gray-400">
              "Being natty is not just a style, it's a way of life."
            </p>
          </div>
          <div className="flex justify-end w-full mb-0">
            <div className="border border-gray-200 rounded-lg p-2">
              <img
                alt="QR code"
                className="aspect-square overflow-hidden rounded-lg"
                height="50"
                src="/placeholder.svg"
                width="50"
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
